# Default values for kafkasummit2022.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: kafkasummit
replicaCount: 1

image:
  repository: tools.radicalbit.io/kafkasummit2022
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: 1.0.0-SNAPSHOT
  pullSecrets:
    - docker-registry-secret
nameOverride: ""
fullnameOverride: ""

labels: {}

# Main config
config:
  bootstrapServer: ks22-brokers-kafka-bootstrap.kafka.svc.cluster.local:9092
  inputTopic: model-input
  outputTopic: model-output
  mode: rest
  hostname: http://iris-model-srv:8000
  namespace: kafkasummit
  modelName: iris-model
  isIstio: true
    
podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
    cpu: 10m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
